---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - name: End of File Fixer
        id: end-of-file-fixer
      - name: Trailing Whitespace Fixer
        id: trailing-whitespace
      - name: Check yaml
        id: check-yaml
      - name: requirements.txt fixer
        id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        name: black formatting

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8 lint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        name: mypy

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
